# Generated by Django 4.2.13 on 2024-07-03 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('short_description', models.TextField(blank=True, max_length=255)),
                ('full_description', models.TextField(blank=True, max_length=2500)),
                ('likes', models.IntegerField(default=0)),
                ('reposts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BlogPostPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_description', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='images/posts/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_photos', to='blogger.blogpost')),
            ],
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['title', 'short_description'], name='blogger_blo_title_b0649e_idx'),
        ),
    ]
