# Generated by Django 4.2.13 on 2024-07-03 10:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='full_description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2500)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='short_description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(150)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, validators=[django.core.validators.MaxLengthValidator(20), django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='blogpostphotos',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/posts/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='blogpostphotos',
            name='photo_description',
            field=models.CharField(blank=True, validators=[django.core.validators.MaxLengthValidator(150)]),
        ),
    ]
