# Generated by Django 4.2.13 on 2024-07-03 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0003_alter_blogpost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostphotos',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_photos', to='blogger.blogpost'),
        ),
    ]
