# Generated by Django 4.2.13 on 2024-07-03 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0004_alter_blogpostphotos_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/posts/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='full_description',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(2500)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='short_description',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(150)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(validators=[django.core.validators.MaxLengthValidator(20), django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.DeleteModel(
            name='BlogPostPhotos',
        ),
    ]
